### ISSUE TITLE
报错 raise UnidentifiedImageError

### ISSUE THREAD

**Issue by ShizukuNia** [Special-Week/youth-version-of-setu4#2]
log：

10-18 18:57:32 [INFO] youth-version-of-setu4 | 图片本地不存在,正在去i.pixiv.re下载
10-18 18:57:34 [SUCCESS] youth-version-of-setu4 | 成功获取图片
10-18 18:57:34 [INFO] nonebot | Matcher <Matcher from youth-version-of-setu4, type=message, priority=10, temp=False> running complete
10-18 18:57:34 [ERROR] nonebot | Running matcher <Matcher from youth-version-of-setu4, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Application\Python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Application\Python\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\Application\Python\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Application\Python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Application\Python\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "D:\Application\Python\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Application\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Application\Python\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "D:\Application\Python\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "D:\Application\Python\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "D:\Application\Python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Application\Python\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "D:\Application\Python\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "D:\Application\Python\lib\site-packages\nonebot\internal\matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "D:\Application\Python\lib\site-packages\nonebot\internal\matcher.py", line 635, in simple_run
    await handler(
  File "D:\Application\Python\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "D:\Application\Python\lib\site-packages\youth-version-of-setu4\__init__.py", line 91, in _
    data = await get_setu(key, r18, num, quality)
  File "D:\Application\Python\lib\site-packages\youth-version-of-setu4\get_data.py", line 52, in get_setu
    data = await asyncio.gather(*tasks)
  File "D:\Application\Python\lib\site-packages\youth-version-of-setu4\get_data.py", line 91, in pic
    image = Image.open(BytesIO(content))
  File "D:\Application\Python\lib\site-packages\PIL\Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001D87FF9E700>
10-18 18:57:34 [DEBUG] nonebot | Stop event propagation

**Comment by Special-Week** [comment]
你有没有更新到最新, 两天前出的这个问题, 后来构造了可用的url

**Comment by ShizukuNia** [comment]
> 你有没有更新到最新, 两天前出的这个问题, 后来构造了可用的url

更新后已解决，谢谢
