### ISSUE TITLE
图片读取报错

### ISSUE THREAD

**Issue by Nighttell** [Special-Week/youth-version-of-setu4#3]
10-19 08:21:27 [ERROR] nonebot | Running matcher <Matcher from youth-version-of-setu4, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "/home/bot/Nighttell/bot.py", line 48, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/usr/local/lib/python3.10/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
R18:False
10-19 08:21:25 [INFO] youth-version-of-setu4 | 图片本地不存在,正在去i.pixiv.re下载

10-19 08:21:27 [SUCCESS] youth-version-of-setu4 | 成功获取图片
10-19 08:21:27 [INFO] nonebot | Matcher <Matcher from youth-version-of-setu4, type=message, priority=10, temp=False> running complete
10-19 08:21:27 [ERROR] nonebot | Running matcher <Matcher from youth-version-of-setu4, type=message, priority=10, temp=False> failed.
Traceback (most recent call last):
  File "/home/bot/Nighttell/bot.py", line 48, in <module>
    nonebot.run(app="__mp_main__:app")
  File "/usr/local/lib/python3.10/site-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/site-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.10/site-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/site-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/site-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/lib/python3.10/site-packages/youth-version-of-setu4/__init__.py", line 91, in _
    data = await get_setu(key, r18, num, quality)
  File "/usr/local/lib/python3.10/site-packages/youth-version-of-setu4/get_data.py", line 52, in get_setu
    data = await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.10/site-packages/youth-version-of-setu4/get_data.py", line 91, in pic
    image = Image.open(BytesIO(content))
  File "/usr/local/lib/python3.10/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0xffff7d811620>

**Comment by Special-Week** [comment]
https://github.com/Special-Week/youth-version-of-setu4/issues/2

**Comment by Nighttell** [comment]
阿里云没有更新orz，清华源才更新了，离谱
