### ISSUE TITLE
启动bot.py时，导入youth-version-of-setu4失败

### ISSUE THREAD

**Issue by KishibeRohan1979** [Special-Week/youth-version-of-setu4#7]
我通过zip包的方式下载了源码，放在了合适的位置启动。

env文件配置如下

```tex
setu_cd = 0
setu_ban = []
setu_withdraw_time = 0
setu_max_num = 30
setu_save = 'C:/Users/Administrator/Desktop/software/nb-my/data/setu4/img'
```

在执行之后出现如下报错

```python
04-23 15:30:12 [ERROR] nonebot | Failed to import "youth-version-of-setu4"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\software\nb-my\bot.py", line 30, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\Desktop\software\python\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\software\python\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\software\python\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\software\python\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\software\python\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\Desktop\software\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\Desktop\software\python\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\software\python\lib\site-packages\youth-version-of-setu4\__init__.py", line 8, in <module>
    from .handle import setu_handle
  File "C:\Users\Administrator\Desktop\software\python\lib\site-packages\youth-version-of-setu4\handle.py", line 17, in <module>
    from .config import config
  File "C:\Users\Administrator\Desktop\software\python\lib\site-packages\youth-version-of-setu4\config.py", line 20, in <module>
    config = Config.parse_obj(get_driver().config)
  File "pydantic\main.py", line 521, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic\env_settings.py", line 38, in pydantic.env_settings.BaseSettings.__init__
    super().__init__(
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Config
setu_save
  value could not be parsed to a boolean (type=type_error.bool)
```

提示**setu_save**的值不能转化为布尔值，但是我看配置说明的时候，这个**setu_save**的值应该是写存放地址，所以是哪里出错了吗

**Comment by Special-Week** [comment]
也许是我的问题， 几天前面向对象重构后没有进行测试， 过两天我再好好检查一下

**Comment by Special-Week** [comment]
https://github.com/Special-Week/youth-version-of-setu4/tree/86c7f29239fa9dfd428a92aa6f3a6a68e9934bb6
你可以试一试重构前的， 功能几乎没有变化， 数据库记录少一点

**Comment by Special-Week** [comment]
已修复
